### ISSUE TITLE
Purchase dialog throws NPE with newer JREs

### ISSUE THREAD

**Issue by bubba0077** [bubba0077/MegaCiv#59]
In newer versions of Java 8, the purchase dialog box throws a NPE on initialization, leading to no dialog being shown:

Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
at javax.swing.text.html.ImageView.updateImageSize(Unknown Source)
at javax.swing.text.html.ImageView.refreshImage(Unknown Source)
at javax.swing.text.html.ImageView.sync(Unknown Source)
at javax.swing.text.html.ImageView.getPreferredSpan(Unknown Source)
at javax.swing.text.FlowView$LogicalView.getPreferredSpan(Unknown Source)
at javax.swing.text.FlowView.calculateMinorAxisRequirements(Unknown Source)
at javax.swing.text.ParagraphView.calculateMinorAxisRequirements(Unknown Source)
at javax.swing.text.html.ParagraphView.calculateMinorAxisRequirements(Unknown Source)
at javax.swing.text.BoxView.checkRequests(Unknown Source)
at javax.swing.text.BoxView.getMinimumSpan(Unknown Source)
at javax.swing.text.html.ParagraphView.getMinimumSpan(Unknown Source)
at javax.swing.text.BoxView.calculateMinorAxisRequirements(Unknown Source)
at javax.swing.text.html.BlockView.calculateMinorAxisRequirements(Unknown Source)
at javax.swing.text.BoxView.checkRequests(Unknown Source)
at javax.swing.text.BoxView.getMinimumSpan(Unknown Source)
at javax.swing.text.html.BlockView.getMinimumSpan(Unknown Source)
at javax.swing.text.BoxView.calculateMinorAxisRequirements(Unknown Source)
at javax.swing.text.html.BlockView.calculateMinorAxisRequirements(Unknown Source)
at javax.swing.text.BoxView.checkRequests(Unknown Source)
at javax.swing.text.BoxView.getPreferredSpan(Unknown Source)
at javax.swing.text.html.BlockView.getPreferredSpan(Unknown Source)
at javax.swing.plaf.basic.BasicHTML$Renderer.<init>(Unknown Source)
at javax.swing.plaf.basic.BasicHTML.createHTMLView(Unknown Source)
at javax.swing.plaf.basic.BasicHTML.updateRenderer(Unknown Source)
at javax.swing.plaf.basic.BasicButtonListener.propertyChange(Unknown Source)
at java.beans.PropertyChangeSupport.fire(Unknown Source)
at java.beans.PropertyChangeSupport.firePropertyChange(Unknown Source)
at java.beans.PropertyChangeSupport.firePropertyChange(Unknown Source)
at java.awt.Component.firePropertyChange(Unknown Source)
at javax.swing.AbstractButton.setText(Unknown Source)
at net.bubbaland.megaciv.client.gui.TechnologyStoreDialog.resetCheckboxes(TechnologyStoreDialog.java:398)
at net.bubbaland.megaciv.client.gui.TechnologyStoreDialog.<init>(TechnologyStoreDialog.java:214)
at net.bubbaland.megaciv.client.gui.AstTablePanel$CivRow.actionPerformed(AstTablePanel.java:731)
at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
at java.awt.Component.processMouseEvent(Unknown Source)
at javax.swing.JComponent.processMouseEvent(Unknown Source)
at java.awt.Component.processEvent(Unknown Source)
at java.awt.Container.processEvent(Unknown Source)
at java.awt.Component.dispatchEventImpl(Unknown Source)
at java.awt.Container.dispatchEventImpl(Unknown Source)
at java.awt.Component.dispatchEvent(Unknown Source)
at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
at java.awt.Container.dispatchEventImpl(Unknown Source)
at java.awt.Window.dispatchEventImpl(Unknown Source)
at java.awt.Component.dispatchEvent(Unknown Source)
at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
at java.awt.EventQueue.access$500(Unknown Source)
at java.awt.EventQueue$3.run(Unknown Source)
at java.awt.EventQueue$3.run(Unknown Source)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
at java.awt.EventQueue$4.run(Unknown Source)
at java.awt.EventQueue$4.run(Unknown Source)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
at java.awt.EventQueue.dispatchEvent(Unknown Source)
at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by LMandtler** [comment]
Hi @bubba0077 ,
I would love to use this software coming Saturday for a round of MegaCiv. However, I can not use the buy function currently. Is it possible, that you create a new release with this bug fixed?
Best,
Leo

**Comment by bubba0077** [comment]
@LMandtler Newest beta release has what you are looking for.

**Comment by LMandtler** [comment]
@bubba0077 Man, you are awesome!
